#include "page.h"

const char cyberpunk_html[] =
    "HTTP/1.1 200 OK\r\n"
    "Content-Type: text/html\r\n"
    "Connection: close\r\n\r\n"

    "<!DOCTYPE html>"
    "<html lang='en'>"
    "<head>"
    "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
    "<title>Pico Cyber Control</title>"

    "<style>"
    ":root{"
    "--bg:#05080f;"
    "--panel:#0c1326;"
    "--neon-pink:#ff2efc;"
    "--neon-cyan:#00ffff;"
    "--neon-green:#00ff9c;"
    "--neon-blue:#00aaff;"
    "}"

    "*{box-sizing:border-box;}"

    "body{"
    "margin:0;"
    "background:radial-gradient(circle at top,#10162f,#05080f);"
    "color:var(--neon-cyan);"
    "font-family:'Segoe UI',system-ui,sans-serif;"
    "display:flex;"
    "align-items:center;"
    "justify-content:center;"
    "min-height:100vh;"
    "}"

    ".panel{"
    "background:linear-gradient(180deg,#0c1326,#060a1a);"
    "border:1px solid rgba(0,255,255,0.3);"
    "border-radius:18px;"
    "padding:24px;"
    "width:92%;"
    "max-width:420px;"
    "box-shadow:"
    "0 0 20px rgba(0,255,255,0.3),"
    "inset 0 0 30px rgba(0,255,255,0.05);"
    "}"

    "h1{"
    "text-align:center;"
    "font-size:22px;"
    "margin:0 0 16px;"
    "letter-spacing:2px;"
    "text-shadow:0 0 12px var(--neon-cyan);"
    "}"

    ".grid{"
    "display:grid;"
    "grid-template-columns:1fr 1fr;"
    "gap:16px;"
    "}"

    ".btn{"
    "height:80px;"
    "border-radius:14px;"
    "border:1px solid currentColor;"
    "background:rgba(0,0,0,0.6);"
    "color:inherit;"
    "font-size:16px;"
    "letter-spacing:1px;"
    "cursor:pointer;"
    "box-shadow:0 0 18px currentColor;"
    "}"

    ".red{color:var(--neon-pink);}"
    ".green{color:var(--neon-green);}"
    ".blue{color:var(--neon-blue);}"
    ".white{color:#ffffff;}"

    ".gyro{"
    "margin-top:18px;"
    "font-size:13px;"
    "}"

    ".bar{"
    "height:6px;"
    "background:#102030;"
    "border:1px solid var(--neon-cyan);"
    "margin:6px 0 10px;"
    "position:relative;"
    "}"

    ".fill{"
    "height:100%;"
    "background:var(--neon-pink);"
    "width:50%;"
    "}"

    ".status{"
    "text-align:center;"
    "margin-top:12px;"
    "font-size:12px;"
    "opacity:0.7;"
    "}"

    "</style>"

    "<script>"
    "function setRequest(c){"
    "fetch('/'+c).then(()=>{"
    "document.getElementById('st').innerText='SYNC: '+c.toUpperCase();"
    "});"
    "}"

    "function updateGyro(){"
    "fetch('/gyro').then(r=>r.json()).then(d=>{"
    "let p=Math.max(-90,Math.min(90,d.pitch));"
    "let r=Math.max(-90,Math.min(90,d.roll));"
    "document.getElementById('pt').innerText=p.toFixed(1)+'°';"
    "document.getElementById('rl').innerText=r.toFixed(1)+'°';"
    "document.getElementById('pb').style.width=(50+p/1.8)+'%';"
    "document.getElementById('rb').style.width=(50+r/1.8)+'%';"
    "});"
    "}"

    "setInterval(updateGyro,200);"
    "</script>"

    "</head>"
    "<body>"

    "<div class='panel'>"
    "<h1>DISPLAY CONTROL</h1>"

    "<div class='grid'>"
    "<button class='btn red' onclick=\"setRequest('red')\">RED</button>"
    "<button class='btn green' onclick=\"setRequest('green')\">GREEN</button>"
    "<button class='btn blue' onclick=\"setRequest('blue')\">BLUE</button>"
    "<button class='btn white' onclick=\"setRequest('white')\">WHITE</button>"
    "</div>"

    "<div class='gyro'>"
    "PITCH: <span id='pt'>0°</span>"
    "<div class='bar'><div id='pb' class='fill'></div></div>"
    "ROLL: <span id='rl'>0°</span>"
    "<div class='bar'><div id='rb' class='fill'></div></div>"
    "</div>"

    "<div class='status' id='st'>SYNC: READY</div>"
    "</div>"

    "</body>"
    "</html>";

const unsigned int cyberpunk_html_len = sizeof(cyberpunk_html) - 1;
